baseURL = "https://notarianni.org/"
defaultContentLanguage = "fr"
publishDir = "docs"
title = "notarianni.org"

[languages]
  [languages.fr]
    languageCode = "fr"
    languageName = "Fran√ßais"
    title = "notarianni.org"
    weight = 1

  [languages.en]
    languageCode = "en"
    languageName = "English"
    title = "notarianni.org"
    weight = 2

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
